### ISSUE TITLE
Suggestion: Animania Compatability

### ISSUE THREAD

**Issue by IdrisQe** [Ocelot5836/BetterAnimals#15]
This one is definitely more of a long-term project given the number of models and textures that would need to be made or altered, but this would go really well with Animania. It already has similar models for Chickens and Sheep, and a few mobs it adds like Goats, but its cows and pigs and some others don't fit with Better Animals' style nearly as much.

**Comment by cybercat5555** [comment]
I do plan on mod compat, but not for Animania. I do not wish to make "anatomically correct" animals. I also plan on my own goats for another mod

**Comment by Sunconure11** [comment]
I vouch for config options, but it looks like that's been dealt with in what I assume will have Cyber's goats.
